export const Session = {
  USER_LOGIN_COMPLETED: 'USER_LOGIN_COMPLETED',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_LOGOUT_COMPLETED: 'USER_LOGOUT_COMPLETED'
};

export const User = {
  USER_SIGNUP_COMPLETED: 'USER_SIGNUP_COMPLETED',
  USER_SIGNUP_FAILED: 'USER_SIGNUP_FAILED'
};
